### ISSUE TITLE
install our system on windows

### ISSUE THREAD

**Issue by Arvi3d** [WFP-Dubai/ETS#154]
Install all required packages and our system on windows and document all steps.

**Comment by Arvi3d** [comment]
1. make all paths in instance script relative.
2. remove all other installation types instead of auto and custom.
3. remove traceback messages
4. minGW must be installed offline
5. create desktop shortcut for instance runserver command

**Comment by predatell** [comment]
1. INSTDIR - not Program Files
2. Check command for loading fixtures
