### ISSUE TITLE
Add command before Compas update

### ISSUE THREAD

**Issue by tcarlander** [WFP-Dubai/ETS#155]
Tobias,

To be in line with the on-going implementation of the COMPAS Data access improvement  project,
you need to perform the SQL*command below in your application, before call the write_waybill procedure.

```
            Set role epic_all identified by writeon;
```

As discussed,  due to the nature of the offline E-waybill  solution, the specific user account will be strored in the E-waybill  Database;
Compas will only stored the generic interface account on the waybill created by E-waybill system, like TESTQW_ISBX002 in this case.

**Comment by Arvi3d** [comment]
done
