### ISSUE TITLE
API for STI to get Data

### ISSUE THREAD

**Issue by tcarlander** [WFP-Dubai/ETS#167]
We need an API for the external systems to be able to access certain data with http & Basic Auth
The reports needed are:
Full Stock Report
Full Waybill Report

**Comment by Arvi3d** [comment]
http://10.11.208.242/ets/api/loading_details/basic/ http://10.11.208.242/ets/api/stock_items/basic/
login: api_user
password: resu_ipa

**Comment by tcarlander** [comment]
Some Data missing for the waybills:
Origin Warehouse, Commodity name
