### ISSUE TITLE
super user must be able to see waybill

### ISSUE THREAD

**Issue by Arvi3d** [WFP-Dubai/ETS#176]

**Comment by tcarlander** [comment]
Loggend in as epic :
TemplateSyntaxError at /ets/waybill/ISBX00211A000017/
Caught DoesNotExist while rendering: Person matching query does not exist.
Request Method: GET
Request URL:    http://10.11.208.242/ets/waybill/ISBX00211A000017/
Django Version: 1.3
Exception Type: TemplateSyntaxError
Exception Value:  
Caught DoesNotExist while rendering: Person matching query does not exist.
Exception Location: /usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 349
Python Executable:  /usr/bin/python
Python Version: 2.7.1
Python Path:  
['/opt/ETS/eggs/django_redis_cache-0.9.2-py2.7.egg',
 '/opt/ETS/eggs/redis-2.4.9-py2.7.egg',
 '/opt/ETS/eggs/psycopg2-2.4.2-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/pip-1.0.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages',
 '/opt/ETS/src',
 '/opt/ETS/eggs/djangoprojectrecipe-1.1.1-py2.7.egg',
 '/opt/ETS/eggs/zc.recipe.egg-1.3.2-py2.7.egg',
 '/opt/ETS/eggs/zc.buildout-1.5.2-py2.7.egg',
 '/opt/ETS/eggs/windmill-1.6-py2.7.egg',
 '/opt/ETS/eggs/coverage-3.5.1-py2.7-linux-x86_64.egg',
 '/opt/ETS/src/django-google-analytics',
 '/opt/ETS/eggs/Pygments-1.4-py2.7.egg',
 '/opt/ETS/src/pyqrcode',
 '/opt/ETS/eggs/PIL-1.1.7-py2.7-linux-x86_64.egg',
 '/opt/ETS/eggs/django_compressor-1.0.1-py2.7.egg',
 '/opt/ETS/eggs/django_native_tags-0.5-py2.7.egg',
 '/opt/ETS/src/django-logicaldelete',
 '/opt/ETS/eggs/django_uni_form-0.9.0-py2.7.egg',
 '/opt/ETS/eggs/django_autoslug-1.4.1-py2.7.egg',
 '/opt/ETS/eggs/docutils-0.8.1-py2.7.egg',
 '/opt/ETS/eggs/django_piston-0.2.3-py2.7.egg',
 '/opt/ETS/eggs/setuptools-0.6c12dev_r88846-py2.7.egg',
 '/usr/lib/python2.7/dist-packages',
 '/opt/ETS/src/django-audit-log',
 '/opt/ETS/src/django-debug-toolbar',
 '/opt/ETS/eggs/django_extensions-0.6-py2.7.egg',
 '/opt/ETS/eggs/django_rosetta-0.6.2-py2.7.egg',
 '/opt/ETS/eggs/South-0.7.3-py2.7.egg',
 '/opt/ETS/eggs/django_appconf-0.4.1-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7']
Server time:    Fri, 2 Dec 2011 13:51:42 +0100
